[build]
  publish = "public"
  command = "hugo --gc --minify -b ${URL}"

[build.environment]
  # Netlify Hugo guide: nastav si verzi, aby se ti to nerozb√≠jelo mezi buildy
  HUGO_VERSION = "0.154.5"
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
  command = "hugo --gc --minify -b ${DEPLOY_PRIME_URL}"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
    srcdir = "."
